export const TRUSTED_ROOT_CERTIFICATES = {
  aws_nitro: {
    label: 'AWS Nitro',
    pem: `-----BEGIN CERTIFICATE-----
MIICETCCAZagAwIBAgIRAPkxdWgbkK/hHUbMtOTn+FYwCgYIKoZIzj0EAwMwSTEL
MAkGA1UEBhMCVVMxDzANBgNVBAoMBkFtYXpvbjEMMAoGA1UECwwDQVdTMRswGQYD
VQQDDBJhd3Mubml0cm8tZW5jbGF2ZXMwHhcNMTkxMDI4MTMyODA1WhcNNDkxMDI4
MTQyODA1WjBJMQswCQYDVQQGEwJVUzEPMA0GA1UECgwGQW1hem9uMQwwCgYDVQQL
DANBV1MxGzAZBgNVBAMMEmF3cy5uaXRyby1lbmNsYXZlczB2MBAGByqGSM49AgEG
BSuBBAAiA2IABPwCVOumCMHzaHDimtqQvkY4MpJzbolL//Zy2YlES1BR5TSksfbb
48C8WBoyt7F2Bw7eEtaaP+ohG2bnUs990d0JX28TcPQXCEPZ3BABIeTPYwEoCWZE
h8l5YoQwTcU/9KNCMEAwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUkCW1DdkF
R+eWw5b6cp3PmanfS5YwDgYDVR0PAQH/BAQDAgGGMAoGCCqGSM49BAMDA2kAMGYC
MQCjfy+Rocm9Xue4YnwWmNJVA44fA0P5W2OpYow9OYCVRaEevL8uO1XYru5xtMPW
rfMCMQCi85sWBbJwKKXdS6BptQFuZbT73o/gBh1qUxl/nNr12UO8Yfwr6wPLb+6N
IwLz3/Y=
-----END CERTIFICATE-----`
  },
  ztbrowser_demo: {
    label: 'ZTBrowser Demo',
    pem: `-----BEGIN CERTIFICATE-----
MIICGjCCAaCgAwIBAgIUaWtm8n3UtuZP3TydpzWBgS2v2+QwCgYIKoZIzj0EAwMw
RDEcMBoGA1UEAwwTenRicm93c2VyLWRlbW8tcm9vdDEXMBUGA1UECgwOWlRCcm93
c2VyIERlbW8xCzAJBgNVBAYTAlVTMB4XDTI2MDMwODE2NDc0NloXDTM2MDMwNTE2
NDc0NlowRDEcMBoGA1UEAwwTenRicm93c2VyLWRlbW8tcm9vdDEXMBUGA1UECgwO
WlRCcm93c2VyIERlbW8xCzAJBgNVBAYTAlVTMHYwEAYHKoZIzj0CAQYFK4EEACID
YgAEzzNKRarIzDUj/VZSUuWyTnLRFljhYcRJCsk+9iSkn01M0+EVCDnmKwFQh/7I
4c6QfQdMaCuKHq3tu3UKoxTp3ep6B1tc4KpIFteoJQOGUFGfguKV3kQtp8y3Hoeq
F5mZo1MwUTAdBgNVHQ4EFgQUix6ZhcOMgbrWtuBZwgjSHHp6jCYwHwYDVR0jBBgw
FoAUix6ZhcOMgbrWtuBZwgjSHHp6jCYwDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjO
PQQDAwNoADBlAjBIAtc0Wy1sj+Q4GrMEPWHtI10RIcpB7T2TZK16vxT29kIruwsm
XqoCL8xzwZT3u/UCMQCu6HnMzLyoEqm7xB8VJ6KxEFdfNleQfzoBAE4HUsoP1WqQ
cuw1iXkn7Qlclld8Rmg=
-----END CERTIFICATE-----`
  }
};

// Keep the active trust anchors extension-local. Narrow this list for production.
export const ACTIVE_TRUSTED_ROOT_IDS = ['aws_nitro', 'ztbrowser_demo'];
